services:
    web:
        container_name: practice-1
        restart: always
        build: .
        ports:
            - "5000:8080"
        links:
            - mongo
        env_file:
            - .env
        environment:
            - MONGO_URI=mongodb://mongo:27017/reto1
        volumes:
            - .:/usr/src/app
    mongo:
        container_name: mongo-practice
        image: mongo
        ports:
            - "27017:27017"
